[package]
name = "gs-music-installer"
version = "1.0.0"
edition = "2021"

[dependencies]
eframe = "0.29"
tokio = { version = "1", features = ["full"] }
which = "7"

[target.'cfg(windows)'.dependencies]
winreg = "0.52"

[profile.release]
opt-level = "z"
lto = true
strip = true
